[features]
seeds = false
[programs.localnet]
minigame = "5d5KPyxuuRQ3DApdxWSCGTgPxb4XBxbwkHpZZCBtzwgU"
[programs.devnet]
minigame = "5d5KPyxuuRQ3DApdxWSCGTgPxb4XBxbwkHpZZCBtzwgU"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p tsconfig.json -t 1000000 tests/*.ts"