[features]
seeds = false
[programs.localnet]
minigame = "2F33SPVaVDnw845AkFHmjP3GtyjkdfBm9cRnwP3EqVi6"
ticketbox = "DJUusxKaSq2p7NiWZgQBAKXRDrrhFcR28vTa7bRxYvYN"
[programs.devnet]
minigame = "2F33SPVaVDnw845AkFHmjP3GtyjkdfBm9cRnwP3EqVi6"
ticketbox = "DJUusxKaSq2p7NiWZgQBAKXRDrrhFcR28vTa7bRxYvYN"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p tsconfig.json -t 1000000 tests/*.ts"