[features]
seeds = false
[programs.localnet]
minigame = "C6EVzNJr8oNJUW3fY3qxuh9MGgdGoSUdPk7RnbRXvxmQ"
ticketbox = "A2yL9vgkAFhXy1j8kQJJ4A9axJ3EsNt129LVpsM1KruH"
[programs.devnet]
minigame = "C6EVzNJr8oNJUW3fY3qxuh9MGgdGoSUdPk7RnbRXvxmQ"
ticketbox = "A2yL9vgkAFhXy1j8kQJJ4A9axJ3EsNt129LVpsM1KruH"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p tsconfig.json -t 1000000 tests/*.ts"